import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import localFont from 'next/font/local';
import './globals.css';
import { ToastProvider } from '@/components/providers/toaster-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <header>
            <nav>
              {/* Show SignInButton if not signed in */}
              <SignedOut>
                <SignInButton mode="modal" />
              </SignedOut>
              {/* Show UserButton if signed in */}
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </nav>
          </header>
          <ToastProvider />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}

